name: test

on:
  workflow_dispatch:

permissions:
    contents: write
    repository-projects: read
jobs:
  build:

    runs-on: ubuntu-latest



    steps:
    - run: |
        git push origin --delete protected-test-branch
    
