name: test

on:
  workflow_dispatch:

permissions:
    contents: write
    repository-projects: read
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: |
        git push origin --delete protected-test-branch
    
