name: Validation

on:
  workflow_dispatch:
  
env: 
  env_var: ${{ vars.ENV_VARIABLE_BRANCH }}
  
jobs:
  Validate:
    runs-on: ubuntu-latest

    steps:
     - name: curl command to list teams
       run: |
         echo $env_var is the variable
       
