name: Validation

on:
  workflow_dispatch:

jobs:
  Validate:
    runs-on: ubuntu-latest

    steps:
     - name: curl command to list teams
       run: |
       
        curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/New-Org234/teams/test_team/members                
       env: 
            GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
        
