name: Validation

on:
  workflow_dispatch:

jobs:
  Validate:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       run: |
        curl \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.TEAM_TOKEN }}"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/teams/TEST_TEAM/members
        
       env:
              TEAM_TOKEN: ${{ secrets.TEAM_TOKEN }}
        
